### ISSUE TITLE
Package for Ubuntu Bionic 18.04 LTS.

### ISSUE THREAD

**Issue by yadakhov** [treasure-data/chef-td-agent#119]
I am unable to install td-agent with Ubuntu Bionic 18.04 LTS.

**Comment by couture-ql** [comment]
It's likely because the current attribute/default.rb is set to [2.2.0](https://github.com/treasure-data/chef-td-agent/blob/master/attributes/default.rb#L15), combined with [install.rb](https://github.com/treasure-data/chef-td-agent/blob/master/recipes/install.rb#L57) deriving the wrong path to install a recent version of td-agent.  Version 2 appears to be deprecated, or at least has been pruned from http://packages.treasuredata.com. 

To fix it you'll need to pin the version to 3.

```
default['td_agent']['version'] = 3
```

Some unhelpful advice: you could always abandon this and go with the [shell-installer](https://tddocs.atlassian.net/wiki/spaces/PD/pages/125435905/Installing+TD+Toolbelt+and+Treasure+Agent#Ubuntu-and-Debian) script, but then you'll need to deploy any configurations you previous defined from this recipe.
